export const SIGN_IN_REQ = "SIGN_IN_REQ";
export const SIGN_IN_OK = "SIGN_IN_OK";
export const SIGN_IN_BAD = "SIGN_IN_BAD";

export const SIGN_OUT_REQ = "SIGN_OUT_REQ";
export const SIGN_OUT_OK = "SIGN_OUT_OK";
export const SIGN_OUT_BAD = "SIGN_OUT_BAD";

export const SIGN_UP_REQ = "SIGN_UP_REQ";
export const SIGN_UP_OK = "SIGN_UP_OK";
export const SIGN_UP_BAD = "SIGN_UP_BAD";

export const SIGNUP_VERIFY_REQ = "SIGNUP_VERIFY_REQ";
export const SIGNUP_VERIFY_OK = "SIGNUP_VERIFY_OK";
export const SIGNUP_VERIFY_BAD = "SIGNUP_VERIFY_BAD";

export const GET_APPOINTMENTS_REQ = "GET_APPOINTMENTS_REQ";
export const GET_APPOINTMENTS_OK = "GET_APPOINTMENTS_OK";
export const GET_APPOINTMENTS_BAD = "GET_APPOINTMENTS_BAD";

export const GET_APPOINTMENT_REQ = "GET_APPOINTMENT_REQ";
export const GET_APPOINTMENT_OK = "GET_APPOINTMENT_OK";
export const GET_APPOINTMENT_BAD = "GET_APPOINTMENT_BAD";

export const GET_USER_APPOINTMENTS_REQ = "GET_USER_APPOINTMENTS_REQ";
export const GET_USER_APPOINTMENTS_OK = "GET_USER_APPOINTMENTS_OK";
export const GET_USER_APPOINTMENTS_BAD = "GET_USER_APPOINTMENTS_BAD";

export const BOOK_APPOINTMENT_REQ = "BOOK_APPOINTMENT_REQ";
export const BOOK_APPOINTMENT_OK = "BOOK_APPOINTMENT_OK";
export const BOOK_APPOINTMENT_BAD = "BOOK_APPOINTMENT_BAD";

export const GET_USERS_REQ = "GET_USERS_REQ";
export const GET_USERS_OK = "GET_USERS_OK";
export const GET_USERS_BAD = "GET_USERS_BAD";

export const GET_PROFILE_REQ = "GET_PROFILE_REQ";
export const GET_PROFILE_OK = "GET_PROFILE_OK";
export const GET_PROFILE_BAD = "GET_PROFILE_BAD";

export const GET_RECOMMENDATIONS_REQ = "GET_RECOMMENDATIONS_REQ";
export const GET_RECOMMENDATIONS_OK = "GET_RECOMMENDATIONS_OK";
export const GET_RECOMMENDATIONS_BAD = "GET_RECOMMENDATIONS_BAD";

export const GET_REVIEWS_REQ = "GET_REVIEWS_OK";
export const GET_REVIEWS_OK = "GET_RECOMMENDATIONS_OK";
export const GET_REVIEWS_BAD = "GET_REVIEWS_BAD";
